# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ee988469bd56d1e39961e0dae1eef758a3c12ecf337caafb0a23ebb848f5fb81705c4cae9fb85f55647fef9c154bc542a8580b7b0525ebc88bc0cb67f4c8bd2d

test:
  secret_key_base: 56eb6c24ec8a395f6565a14ab0ad0a51658754b03502e7c186ca051bc7c8e45b5dbe0717c9ed41952192071b085d2fc19409be9c0c4abe924e83b04326598576

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
